vim9script

set nocompatible
syntax on

language en_US

set termguicolors
set background=light
colorscheme catppuccin_latte

# enable lightline
set laststatus=2

g:lightline = { 'colorscheme': 'catppuccin_latte' }

if has('gui_running')
    set guioptions=
    set guifont=Maple\ Mono\ SC\ NF:h12
    set guicursor+=a:blinkon0
endif

if has('gui_win32')
    # set renderoptions=type:directx,gamma:1.0,taamode:2
    set renderoptions=type:directx,geom:1,renmode:4
endif
